#!/bin/sh /etc/rc.common
# Copyright (C) 2015 brglng@github.com

START=99
STOP=99

start() {
        service_start /userdisk/.syncthing/syncthing -home /userdisk/.syncthing/config 2>&1 | logger -t syncthing &
}

stop() {
        service_stop /userdisk/.syncthing/syncthing -home /userdisk/.syncthing/config
}
